### ISSUE TITLE
No longer displays listing of favorited posts. Page is blank.

### ISSUE THREAD

**Issue by fluxxagency** [hberberoglu/wp-favorite-posts#14]
The plugin has worked perfectly for us for the past year but recently it's stopped working. We use it to favorite video posts on our site and compile a favorites list. The favorites list is now blank. Nothing is being listed although the data is available. When we favorite something and check the list, the "Clear favorites" link no longer displays so it works to some extent, just doesn't output anything. I'm thinking it may be the latest Wordpress update (4.2.2).

**Comment by minordv8** [comment]
I'm having the same issue but it was already working on Wordpress 4.2.2. It was when I updated the wp-favorites-posts plugin from version 1.6.2 to 1.6.3. From what I can see it might be related to the statistical feature.

**Comment by lightson** [comment]
Seeing the same issue on wordpress 4.7.5.

Adding/removing works fine - as does the favorites widget - however the [wp-favorite-posts] shortcode displays nothing except "clear favorites' (clicking clear achieves the expected outcome)
