### ISSUE TITLE
PHP v7.1 fatal error:Uncaught Error: [] operator not supported for strings

### ISSUE THREAD

**Issue by dclprogramming** [hberberoglu/wp-favorite-posts#29]
When using wp-favorite-posts plugin with php v7.1 I am getting a fatal error upon clicking to favorite a post..."Uncaught Error: [] operator not supported for strings". Any ideas?

**Comment by sambasile** [comment]
Same as issue https://github.com/hberberoglu/wp-favorite-posts/pull/30?

**Comment by hberberoglu** [comment]
This should be fixed after merge of pr in https://github.com/hberberoglu/wp-favorite-posts/pull/30
